# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3813c5a17ff76126798d69dd305dad3b4bf4ee31c98150d891e64094c7563797168e3d16907395afe617b7183d3a0e8f3e9c676ab8332fc9a9414fa6a60e9667

test:
  secret_key_base: 8cd81f563a6b646a8f0af81872add0303b7c4fa8a32e80fa860713da6f5188f814177c69729bcdcd2191fd95ffa4c07455e2fd0a716213c24fef21d08d2d8185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
